conf/VASAutoBalance.conf.dist
There was a typo in the config: "VASAutoBalance.DisableID" instead of "VASAutoBalance.DisabledID".
See the appropriate line in the code:
https://github.com/azerothcore/mod-vas-autobalance/blob/6327f3fe824095df43cae824311724acfe1cd1aa/src/VASAutoBalance.cpp#L208
=> fix typo in config

src/AutoBalance.cpp
Currently, when OnPlayerLeaveAll is called, the player is still counted in GetPlayersCountExceptGMs so switching to a regular decrements, as it is called once per player leaving the map, allows for it to properly recalculate the stats of monsters as players leave the map. This commit also changes the instance of GetPlayersCountExceptGMs in OnPlayerEnterAll to a simple increment as it is called once per player entering the map as well.
=> Correct player leave stat recalc

conf/AutoBalance.conf.dist, src/AutoBalance.cpp
- Add a new config option "MinManaModifier". There's "MinHPModifier", "MinDamageModifier" but no option for a minimum Mana modifier. This is useful because sometimes the Mana of the creatures can drop too low so that they cannot use their spells anymore (e.g. Ragefire Chasm, creature "Ragefire Shaman", entering with level 16 character). This way you can specify a minimum just like for HP or damage.
- Add a new config option "DungeonScaleDownXP". If enabled this option ensures that the player always gets the same XP as if he entered the dungeon with a full group. This can be used to slow down leveling especially when playing solo (some players don't want to gain multiple levels per dungeon run).
- Removed the unused option "AutoBalance.Instances"
- Also removed "numPlayer" from the code as …
=> feat(Config): Add config options "MinManaModifier", "DungeonScaleDownXP"; remove unused option "Instances"

src/AutoBalance.cpp
The option "DisabledID" cannot work because it is read into the map "forcedCreatureIds" with value "0":
https://github.com/azerothcore/mod-autobalance/blob/502643291a10803caa6b4b50492d5653c316f418/src/AutoBalance.cpp#L194
But this value is never checked:
https://github.com/azerothcore/mod-autobalance/blob/502643291a10803caa6b4b50492d5653c316f418/src/AutoBalance.cpp#L545-L548
I implemented an improved fix as PR #30 was abandoned:
- Rename "GetForcedCreatureId" to "GetForcedNumPlayers", as that's what the function actually does
- "GetForcedNumPlayers" returns -1 if the creature ID is not found in the map (0 is used for "DisabledID"!)
- If "GetForcedNumPlayers" returns 0 the creature won't be scaled (which is what "DisabledID" is meant to do)
- Move the check to the beginning of the function …
=> fix(AllCreatureScript): Fix option "DisabledID"

conf/AutoBalance.conf.dist, src/AutoBalance.cpp
Adds separate scaling for bosses, in the form of a conf option BossInflectionMult, which is multiplied by the regular inflection point for the content if the creature is a dungeon boss.
Closes https://github.com/azerothcore/mod-autobalance/issues/47
=> Add boss scaling

conf/AutoBalance.conf.dist, src/AutoBalance.cpp
Creates a check to see if the module is enabled in the config before announcing it. Doesn't make any sense to announce the module if it isn't even running.
Currently untested, only know that it compiles.
=> Only announce the module if it is also enabled

conf/AutoBalance.conf.dist, src/AutoBalance.cpp
Adds options to allow:
- Setting per-dungeon minimum player count
- Setting per-dungeon inflection value
- Setting per-dungeon boss inflection value
All options are disabled by default.
=> feat: Add Per-dungeon scaling options

src/AutoBalance.cpp
Scale ratio was being converted to unsigned int so when there was less than `maxPlayerCount` players in the group, the gold reward would always be 0 after looting when using `DungeonScaleDownMoney = 1`.
=> Fix for dungeon gold always scaled to 0

README.md, acore-module.json, conf/AutoBalance.conf.dist, src/AutoBalance.cpp
This PR gives more control to the administrator as to how to scale creatures in instances. This is done in several ways.
- create new raid settings for 15/20/40 player raids
- create `CurveFloor` and `CurveCeiling` settings per instance size to raise the floor or lower the ceiling of the multiplier curve
- CurveFloor can be raised to prevent lower player counts from being too easy when higher InflectionPoint values are used
- CurveCeiling can be lowered to allow a different multiplier than 1.0 at max players. It can also be raised above 1.0 to increase difficulty across all player counts in a non-linear way.
- deprecate `BossInflectionMult` in favor of settings for each instance type (dungeon, H.dungeon, raid, H.raid) or even each instance size.
- the old setting is still used if present …
=> (features) Add curveFloor and curveCeiling settings, expand raid types, CCDuration, others

src/AutoBalance.cpp
Some characters were crashing the server on login with AutoBalance enabled. Disabling AutoBalance in the config file resolved the issue. I suspect this was because AB was adjusting the aura duration for auras with invalid or non-existent durations.
This PR adds some additional checks to ensure that the aura is valid for adjustment. Applying it to my local server resolved the server crashes.
=> Fix: add checks to CCDuration adjustment

.gitignore, conf/AutoBalance.conf.dist, src/AutoBalance.cpp
Thanks to user @alaxandir for bringing the `DungeonsOnly=0` issue to my attention.
The `AutoBalance.DungeonsOnly=0` setting appears to have never worked correctly. It was trying to balance creatures outside instance maps, which is currently outside the scope of this project. I have removed the setting and left a warning that it has been deprecated and is not processed.
I then added the  `AutoBalance.Enable.*` settings which fulfill the promise of `DungeonsOnly` by allowing the administrator to turn scaling on and off per instance type and size.
Finally, I did more code cleanup and added comments throughout the code base.
Closes #126
=>  Remove `AutoBalance.DungeonsOnly`, replace with better `AutoBalance.Enable.*` settings

src/AutoBalance.cpp
Resolves an issue where upon logging in, auras applied to the player that were cast by a non-existent caster (like a player who is not online) causes the server to crash. Adds additional checks to ensure that the caster and target objects are valid before initiating further function calls.
Closes https://github.com/azerothcore/mod-autobalance/issues/129
=> Fix: Crash when the caster of an aura is a player and is not online

src/AutoBalance.cpp
- Fixes reported issue #135 (thanks Discord user `dreathean`!) where setting `AutoBalance.LevelScaling` to 0 would cause all creatures to appear as dead (but still active and aggro'able). This was due to some incorrect `if` statements that were disabling health, mana, and damage modifier calculations for creatures when LevelScaling is disabled.
- Fixed an unreported issue where creatures that died but were then revived would count towards the average creature level calculation multiple times.
- Closes #135
- user reports
- personal testing
- builds clean, tests well with two players (no dead creatures that should be alive)
- `.die` and `.revive` work as expected without changing the average map level calculation
For #135 :
1. Set `AutoBalance.LevelScaling` to `0` and enter any dungeon. …
=> Fix `AutoBalance.LevelScaling=0` bug and mapstat average bug

src/AutoBalance.cpp
- no longer does expansion-level adjustments of creature HP and Damage if LevelScaling is disabled
- Closes #137 
- HP/Damage multipliers (`.ab creaturestat`) no longer change as the player changes level
- Enabling LevelScaling still works as expected
- Enter instance at a vanilla level (1-60)
- Check creature multipliers (`.ab creaturestat`)
- Change level to 70 or 80
- Check creature multipliers (`.ab creaturestat`) are still the same
=> Fix: Creature HP/Damage should not scale if LevelScaling is disabled

src/AutoBalance.cpp
This will fix a server crash that occurs during a faction change when autobalance is present.
=> Fixed Null Ptr

src/AutoBalance.cpp
- Scales playerDamageRequired based on previous remaining damage and new scaling factor
- Closes #143 
- Dmg mob less than 50%, level up, kill => Get Loot
- Dmg mob more than 50%, level up, kill > Get Loot
1. Same as above
=> Dmg loot fix

conf/AutoBalance.conf.dist, src/AutoBalance.cpp
Thought you got rid of me?
I've focused some time on improving the "top of the config" settings in this PR. For your consideration:
Major Features:
- Added the ability to disable specific instance IDs (`AutoBalance.Disable.PerInstance`)
- Deprecated `AutoBalance.PerDungeonPlayerCounts` in favor of the `AutoBalance.MinPlayers.*` series, which allows setting much more granular MinPlayer settings
**AutoBalance.Disable.***
Specific InstanceIDs can be disabled now using `AutoBalance.Disable.PerInstance`. I also reworked the logic behind the other `AutoBalance.Disable.*` settings to store the disabled state per-map-instance, meaning it only has to be calculated once. 
A config reload will re-evaluate if a map-instance needs to be enabled/disabled, and will adjust the creatures accordingly. No …
=> Add per-instance disable, rework MinPlayers, enhance .ab mapstats output, improve resillience

.github/ISSUE_TEMPLATE/bug_report.yml, README.md, conf/AutoBalance.conf.dist, src/AutoBalance.cpp
This is a fairly major rewrite of large parts of AutoBalance. While the user-facing side of things (the .conf file) is hardly changed at all, the internals behind it are quite different.
**Observable changes**
- Handle damage and healing that doesn't come from a creature (world damage, self-damage, NPC healing, etc)
- Destructible buildings have the damage done to them scaled appropriately based on the scaling settings
- More reliable boss and boss summon detection - both get treated as bosses for multipliers
- Rewrite of in-combat locking for players leaving the instance during combat - if any player in the instance is in combat, the difficulty only goes UP until combat ends
- Reduce "level up animation" events on creatures by setting their level before they're spawned into the world
- …
=> World damage/healing, destructible buildings, multiplier rewrite, logging improvements

src/AutoBalance.cpp
- Fixes crashing issue when the summoner of a creature no longer exists and `.ab creaturestat` is used.
- Add `creatureIDsThatAreNotClones` list to statically exclude creature IDs that shouldn't have their current health and mana values copied from the summoner.
- Closes #160 
- Closes #161 
- Builds
- Works great on Attumen the Huntsman
1. `.go xyz -11144.177734 -1903.518677 49.890297 532`
2. Clear trash and engage Midnight
3. DPS Attumen down to 25%
4. Observe that the new combined creature has the health of Midnight (higher health of the two)
5. Target the combined creature and do `.ab creaturestat`
6. Observe the server not crashing
=> Bug Fixes: Fix `.ab creaturestat` crash, add `creatureIDsThatAreNotClones`

src/AutoBalance.cpp, src/Message.cpp, src/Message.h
I have added internationalized text support for client prompts in Korean, French, German, Simplified Chinese, Traditional Chinese, Spanish, and Russian for all prompts in the game.
- Closes
I successfully compiled on Ubuntu 22.04 without any errors or warnings. Since it's just text internationalization, I verified using two characters with Simplified Chinese and English clients, and didn't find any issues.
The following are some version information and parameters during compilation:
- CMake version: 3.22.1
- Clang version: 14.0.0
-  AzerothCore revision: b6ee4f49cfbf 2024-02-13 19:21:13 +0000 (master branch)
1. Upon entering the game, I selected a character and entered a random instance to check if the prompt messages have been internationalized.
2. Using GM privileges, I executed the .ab …
=> Feat: In-game hints support internationalized text.

src/ABAllCreatureScript.cpp, src/ABAllMapScript.cpp, src/ABAllMapScript.h, src/ABCommandScript.cpp, src/ABCommandScript.h, src/ABConfig.h, src/ABCreatureInfo.h, src/ABGameObjectScript.cpp, src/ABGlobalScript.cpp, src/ABGlobalScript.h, src/ABMapInfo.h, src/ABPlayerScript.cpp, src/ABScriptMgr.cpp, src/ABScriptMgr.h, src/ABUnitScript.cpp, src/ABUnitScript.h, src/ABUtils.cpp, src/ABUtils.h, src/ABWorldScript.cpp, src/ABWorldScript.h, src/AutoBalance.cpp, src/Message.cpp, src/Message.h
=> fix codestyle and add enabled hook lists for performance improvement
